### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by huangqiongyan123** [6666ev/ML-LJP#3]
您好，我最近在投一篇LJP相关的工作，审稿人要求补充新数据集上的实验，由于时间非常紧急，我也找不到其他baseline的代码，所以没办法再重新跑。不知道您能不能把您处理过后的数据集分享给我，我直接将您的模型和您跑的baseline的结果作为我的baseline的结果。这是我的邮箱huangqiongyannn@gmail.com，如果可以的话，不知道您能不能把数据集发送到我的邮箱里面，真的非常感激！！！！！！！！！！！！！！！！！！！

**Comment by 6666ev** [comment]
数据集见readme中提供的google drive链接可下载

**Comment by huangqiongyan123** [comment]
非常感谢您的回复。我看您论文里面的数据集统计表格里面的罪名标签一共是只有42个对吗？我这边根据google drive链接下载的数据集统计出来的是有149个罪名，训练集的大小以及测试集的大小按照8:1的比例计算似乎也对不上。不知道您这边可否将您处理之后的数据集分享给我，我这边想延用您的data processing pipeline，到时候会在论文中注明出处。如果可以，非常感激！！！！！！

**Comment by 6666ev** [comment]
处理后数据在laic- processed文件夹下，罪名数量在c2i.json中，train/valid/test数据集比例您仔细核对下

**Comment by huangqiongyan123** [comment]
看到啦，非常感谢！！！
